name: Static Code Analysis
on: 
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '.github/templates/**'
      - 'modules/**'
jobs:
  code-analysis:
    name: Run Code Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Test with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./modules
          framework: terraform    
          output_format: cli
          output_file_path: console,results.sarif 

      - name: Test with tfsec
        if: success() || failure()
        uses: aquasecurity/tfsec-action@v1.0.0