name: Static Code Analysis
on: 
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '.github/templates/**'
      - 'modules/**'
jobs:
  code-analysis:
    name: Run Code Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Clone repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Test with Checkov
        uses: bridgecrewio/checkov-action@f967808197a8d784d3e72919f38c3ff0cda7884e # v12.3122.0
        with:
          directory: ./modules
          framework: terraform    
          output_format: cli
          output_file_path: console,results.sarif 

      - name: Test with tfsec
        if: success() || failure()
        uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6 # v1.0.3
