name: Static Code Analysis
on:
  pull_request:
    branches: 
      - 'main'
  #push:
  #  tags:
  #    - v1.0.0  
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./modules
          framework: terraform
  #tflint:                                     
      #runs-on: ubuntu-latest
      #steps:
      #  - name: Checkout Repository
      #    uses: actions/checkout@v2
          
      #  - name: Set up TFLint
      #   uses: terraform-linters/setup-tflint@v3 # This is the latest version in the marketplace; however, I always encounter an error indicating that the version is not stable.
    
      # - name: Test with TFLint
      #    run:
      #        tflint --chdir ./modules --format compact

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
