---
name: Trigger AWX on push to master

on:
  push:
    branches:
      - main
    paths:
      - modules/**

permissions: {}

jobs:
  trigger_awx:
    uses: hpi-schul-cloud/infra-tools/.github/workflows/trigger-awx.yaml@master
    with:
      job_id: 33
    secrets:
      AWX_TOKEN: ${{ secrets.AWX_TOKEN }}
