
# https://terraform-docs.io/how-to/configuration-file/
# https://terraform-docs.io/user-guide/configuration/
# file not inside workflows folder, as it would create another githubAction

formatter: markdown table

sections:
  show-all: true

content: |-

  {{ .Providers }}
  {{ .Modules }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Requirements }}
  {{ .Resources }}

sort:
  enabled: true
  # other options: name, required, type (expects string) 
  by: required

# all default values 
settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true